package org.ntnu.idi.idatt2106.sparesti.sparestibackend.model.enums;

import lombok.RequiredArgsConstructor;

/**
 * Types of challenges generated by the system.
 */
@RequiredArgsConstructor
public enum DefaultChallengeType {
    CIGAR("RØYK"),
    CLOTHING("KLÆR"),
    COFFEE("KAFFE"),
    SNUFF("SNUS"),
    SNACKS("SNACKS"),
    TRANSPORTATION("TRANSPORT");

    private final String type;
}
