package org.ntnu.idi.idatt2106.sparesti.sparestibackend.model.enums;

/**
 * Types of challenges generated by the system.
 */
public enum DefaultChallengeType {
    CIGAR,
    CLOTHING,
    COFFEE,
    SNUFF,
    SNACKS,
    TRANSPORTATION
}
